label_2_text = {
    "__label__1": "Amazon_Instant_Video",
    "__label__2": "Apps_for_Android",
    "__label__3": "Automotive",
    "__label__4": "Baby",
    "__label__5": "Beauty",
    "__label__6": "Books",
    "__label__7": "CDs_and_Vinyl",
    "__label__8": "Cell_Phones_and_Accessories",
    "__label__9": "Clothing_Shoes_and_Jewelry",
    "__label__10": "Digital_Music",
    "__label__11": "Electronics",
    "__label__12": "Grocery_and_Gourmet_Food",
    "__label__13": "Health_and_Personal_Care",
    "__label__14": "Home_and_Kitchen",
    "__label__15": "Kindle_Store",
    "__label__16": "Movies_and_TV",
    "__label__17": "Musical_Instruments",
    "__label__18": "Office_Products",
    "__label__19": "Patio_Lawn_and_Garden",
    "__label__20": "Pet_Supplies",
    "__label__21": "Sports_and_Outdoors",
    "__label__22": "Tools_and_Home_Improvement",
    "__label__23": "Toys_and_Games",
    "__label__24": "Video_Games",
}
